ITLAManage/Controllers/AsignaturaController.cs
using ITLAManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManageITLA.Controllers
{
    public class AsignaturaController : Controller
    {
        public ActionResult Index()
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();
                using(var db = new ManageITLAContext()){ return View(db.Asignaturas.ToList()); } 
            }
            catch (Exception){ throw; }
        }

        [HttpGet]
        public ActionResult AgregarAsignatura(){ return View(); }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarAsignatura(Asignaturas a)
        {
            try
            {
                using(var bd = new ManageITLAContext())
                {
                    a.FechaRegistro = DateTime.Now;
                    bd.Asignaturas.Add(a);
                    bd.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception){ throw; }
        }

        [HttpGet]
        public ActionResult EditarAsignatura(int id)
        {
            try
            {
                using (var bd = new ManageITLAContext())
                {
                    return View(bd.Asignaturas.Find(id));
                }

            }
            catch (Exception) { throw; }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarAsignatura(Asignaturas a) 
        {
            try
            {
                using(var bd = new ManageITLAContext())
                {
                    var asignEdit = bd.Asignaturas.Find(a.IDAsignatura);
                    a.Nombre = asignEdit.Nombre;
                    bd.SaveChanges();
                    return RedirectToAction("Index");
                }
                
            }
            catch (Exception){throw;}
        }

        public ActionResult BorrarAsignatura(int id)
        {
            try
            {
                using (var bd = new ManageITLAContext())
                {
                    bd.sp_borrarAsignatura(id);
                    bd.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception){throw;}
        }
    }
}

ITLAManage/Controllers/EstudianteController.cs
using ITLAManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManageITLA.Controllers
{
    public class EstudianteController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            try{ 
                using (var db = new ManageITLAContext()) 
                {
                    return View(db.Estudiantes.ToList()); 
                }
            } 
            catch (Exception){ throw; }
        }

        [HttpGet]
        public ActionResult Agregar(){ return View(); }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(Estudiantes e)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new ManageITLAContext())
                {
                    e.FechaRegistro = DateTime.Now;
                    db.Estudiantes.Add(e);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error ", ex);
                return View();
            }
            
        }

        [HttpGet]
        public ActionResult Editar(int? id = null){

            if (id == null)
                RedirectToAction(nameof(Index));

            try
            {
                using(var db = new ManageITLAContext()) 
                {
                    var EstEnEdit = db.Estudiantes.Find(id);
                    return View(EstEnEdit);
                }
            }
            catch (Exception){throw;}

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Estudiantes e)
        {
            try
            {

                if (!ModelState.IsValid)
                    return View();

                using(var db = new ManageITLAContext())
                {
                    var eEdit = db.Estudiantes.Find(e.IDEstudiante);
                    eEdit.Nombre = e.Nombre;
                    eEdit.Apellido = e.Apellido;
                    eEdit.FechaNacimiento = e.FechaNacimiento;
                    eEdit.FechaRegistro = DateTime.Now;
                    eEdit.Sexo = e.Sexo;

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception){throw;}
        }

        public ActionResult Borrar(int id)
        {
            try
            {
                using(var db = new ManageITLAContext())
                {
                    Estudiantes e = db.Estudiantes.Find(id);
                    db.Estudiantes.Remove(e);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception){throw;}
        }

        [HttpGet]
        public ActionResult AgregarMateriaEstudiante(int? id = null)
        {
            if (id == null)
                return RedirectToAction(nameof(Index));

            try
            {
                ViewBag.IDEstudiante = id;
                return View();
            }
            catch (Exception) { throw; }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarMateriaEstudiante(EstudianteSeleccionAsignatura esa)
        {
            try
            {
                if (!ModelState.IsValid || esa.Cuatrimestre == null)
                    return View();

                using (var db = new ManageITLAContext())
                {
                    esa.IDEstudiante = int.Parse(Request.Form["IDEstudiante"]);
                    esa.IDAsignatura = int.Parse(Request.Form["IDAsignatura"]);

                    var dtsEsa = from e in db.EstudianteSeleccionAsignatura
                                 where esa.IDEstudiante == e.IDEstudiante
                                 select e;

                    esa.FechaSeleccion = DateTime.Now;

                    foreach (var est in dtsEsa)
                    {
                        if (est.IDEstudiante == esa.IDEstudiante && est.IDAsignatura == esa.IDAsignatura)
                        {
                            ViewBag.Msg = "Este estudiante ya tiene esta materia.";
                            return View(esa);
                        }
                    }

                    db.EstudianteSeleccionAsignatura.Add(esa);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult EliminarMateriaEstudiante(int? IDEst, int? IDAsign)
        {
            try
            {
                if (IDEst == null || IDAsign == null)
                    return RedirectToAction(nameof(Index));

                using (var bd = new ManageITLAContext())
                {

                    var idAsig = from dp in bd.EstudianteSeleccionAsignatura
                                 join a in bd.Asignaturas on dp.IDAsignatura equals a.IDAsignatura
                                 where dp.IDEstudiante == IDEst && a.IDAsignatura == IDAsign
                                 select dp;

                    bd.EstudianteSeleccionAsignatura.Remove(idAsig.First());
                    bd.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception) { throw; }
        }
    }
}

ITLAManage/Controllers/ProfesorController.cs
using ITLAManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManageITLA.Controllers
{
    public class ProfesorController : Controller
    {
        public ActionResult Index()
        {
			try
			{ using(var db = new ManageITLAContext()){ return View(db.Profesores.ToList()); } }
			catch (Exception){ throw; }
        }

        public ActionResult AgregarProfesor(){ return View(); }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarProfesor(Profesores p)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                using(var db = new ManageITLAContext())
                {
                    p.FechaRegistro = DateTime.Now;
                    DetalleProfesorAsignatura dpa = new DetalleProfesorAsignatura();
                    dpa.IDProfesor = p.IDProfesor;
                    dpa.IDAsignatura = p.IDAsignatura;
                    dpa.Cuatrimestre = p.Cuatrimestre;
                    dpa.FechaAsignacion = DateTime.Now;

                    db.DetalleProfesorAsignatura.Add(dpa);
                    db.Profesores.Add(p);
                    
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                
            }
            catch (Exception){throw;}
        }

        [HttpGet]
        public ActionResult EditarProfesor(int id)
        {
            try{using(var db = new ManageITLAContext()){return View(db.Profesores.Find(id));}}
            catch (Exception){throw;}
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarProfesor(Profesores p)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                using(var db = new ManageITLAContext())
                {
                    var pEdit = db.Profesores.Find(p.IDProfesor);
                    pEdit.Nombre = p.Nombre;
                    pEdit.Apellido = p.Apellido;
                    pEdit.Sexo = p.Sexo;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception){ throw; }
        }

        public ActionResult BorrarProfesor(int id)
        {
            try 
            {
                if (!ModelState.IsValid)
                    return RedirectToAction("Index");
                using (var db = new ManageITLAContext()) 
                {
                    db.sp_borrarProfesor(id);
                    db.SaveChanges();
                    return RedirectToAction("Index"); 
                } 
            }
            catch (Exception) { throw; }
        }

        public ActionResult AsignaturasList()
        {
            using(var db = new ManageITLAContext()){ return PartialView(db.Asignaturas.ToList()); }
        }

        [HttpGet]
        public ActionResult AgregarMateriaProfesor(int id)
        {
            try
            {
                ViewBag.IDProfesor = id;
                return View();
            }
            catch (Exception){throw;}
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarMateriaProfesor(DetalleProfesorAsignatura dpa)
        {
            try
            {
                if (!ModelState.IsValid || dpa.Cuatrimestre == null)
                    return View();

               using(var db = new ManageITLAContext())
                {
                    Boolean todoBien = false;
                    dpa.IDProfesor = int.Parse(Request.Form["IDProfesor"]);
                    dpa.IDAsignatura = int.Parse(Request.Form["IDAsignatura"]);
                    var detailsprof = from p in db.DetalleProfesorAsignatura
                               where p.IDProfesor == dpa.IDProfesor
                               select p;
                    dpa.FechaAsignacion = DateTime.Now;

                    foreach (var prof in detailsprof) {
                        if (prof.IDProfesor == dpa.IDProfesor && prof.IDAsignatura == dpa.IDAsignatura)
                        {
                            ViewBag.Msg = "Este profesor ya tiene esta materia.";
                            todoBien = false;
                            return View(dpa);
                        }
                        todoBien = true;
                    }

                    if(todoBien)
                    {
                        db.DetalleProfesorAsignatura.Add(dpa);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult EliminarMateriaProfesor(int? IDProf, int? IDAsign, bool crct)
        {
            try
            {
                if (IDProf == null || IDAsign == null)
                    return RedirectToAction("Index");

                using(var bd = new ManageITLAContext())
                {

                    var idAsig = from dp in bd.DetalleProfesorAsignatura
                                 join a in bd.Asignaturas on dp.IDAsignatura equals a.IDAsignatura
                                 where dp.IDProfesor == IDProf && a.IDAsignatura == IDAsign
                                 select dp;

                    if (!crct)
                        bd.sp_borrarProfesor(IDProf);
                    else
                        bd.DetalleProfesorAsignatura.Remove(idAsig.First());

                    bd.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception){throw;}
        }

    }
}

ITLAManage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @Html.ActionLink("ITLA Admin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">@Html.ActionLink("Estudiantes", "Index", "Estudiante", new { }, new { @class = "nav-link text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("Profesores", "Index", "Profesor", new { }, new { @class = "nav-link text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("Asignaturas", "Index", "Asignatura", new { }, new { @class = "nav-link text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("Acerca de", "About", "Home", new { }, new { @class = "nav-link text-dark" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted text-center">
        <p style="margin:10px;"><strong>&copy; SB Meek Company </strong> - All rights reserved (@DateTime.Now.Year)</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ITLAManage/Views/Shared/_Layout.old.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>